import { defineBackend } from "@aws-amplify/backend";
import { Duration } from "aws-cdk-lib";
import { PolicyStatement } from "aws-cdk-lib/aws-iam";
import { Queue } from "aws-cdk-lib/aws-sqs";
import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";
import { auth } from "./auth/resource.js";
import { beaverApi } from "./functions/beaver-api/resource.js";

const backend = defineBackend({
  auth,
  beaverApi,
});

const stack = backend.createStack("beaver-jobs-queue");
const queue = new Queue(stack, "BeaverJobsQueue", {
  // Must be >= Lambda timeout; keep comfortably above to avoid duplicate SQS deliveries.
  visibilityTimeout: Duration.minutes(60),
});

// @ts-ignore - function resources are generated by Amplify and typed loosely.
backend.beaverApi.resources.lambda.addEnvironment("BEAVER_JOB_QUEUE_URL", queue.queueUrl);
// @ts-ignore - function resources are generated by Amplify and typed loosely.
backend.beaverApi.resources.lambda.addEventSource(
  new SqsEventSource(queue, {
    batchSize: 1,
    maxBatchingWindow: Duration.seconds(0),
  }),
);
// @ts-ignore - function resources are generated by Amplify and typed loosely.
queue.grantConsumeMessages(backend.beaverApi.resources.lambda);
// @ts-ignore - function resources are generated by Amplify and typed loosely.
queue.grantSendMessages(backend.beaverApi.resources.lambda);

// Allow reading user-provided S3 paths (list + head/get) across buckets.
// Required for s3://<bucket>/<prefix> jobs that are outside BEAVER_JOB_BUCKET.
// @ts-ignore - function resources are generated by Amplify and typed loosely.
backend.beaverApi.resources.lambda.addToRolePolicy(
  new PolicyStatement({
    actions: ["s3:ListBucket", "s3:GetBucketLocation"],
    resources: ["arn:aws:s3:::*"],
  }),
);
// @ts-ignore - function resources are generated by Amplify and typed loosely.
backend.beaverApi.resources.lambda.addToRolePolicy(
  new PolicyStatement({
    actions: ["s3:GetObject"],
    resources: ["arn:aws:s3:::*/*"],
  }),
);
